### ISSUE TITLE
Multiple tabs taking up too much space

### ISSUE THREAD

**Issue by iansquenet** [leadweedy/Firefox-Proton-Square#12]
I remember in Firefox 88 the tabs got significally smaller when there were a lot of tabs open, how can I achieve it?

![image](https://user-images.githubusercontent.com/36297463/200145913-8df715b7-a7e3-4e15-a50a-3180c430c20d.png)

**Comment by leadweedy** [comment]
within `about:config`, you can set `browser.tabs.tabMinWidth` to `150` px or desired width. default in current FF (108) is `76` px.
