### ISSUE TITLE
Tab separators aren't displayed properly on Firefox 108

### ISSUE THREAD

**Issue by BrunaPitanga** [leadweedy/Firefox-Proton-Square#13]
![tab separators](https://user-images.githubusercontent.com/115604365/203606155-8eb26673-0195-43d4-bc4c-e6332ef9fcba.png)

 - OS: Windows
 - Firefox version: Developer 108.0b5

**Comment by EktoHunter** [comment]
Since today's update, this also happens on MacOS: 
<img width="840" alt="grafik" src="https://user-images.githubusercontent.com/23218251/207720412-9fe69a44-3ab6-435b-9d28-0758717a807d.png">

**Comment by kaos-55** [comment]
Apparently the developer hasn't replied, so try to fix it.

Before the fix
![firefoximg1](https://user-images.githubusercontent.com/86812371/207794937-8667c365-8a85-465a-adf4-525d90fe43d0.png)

After the fix.
![firefoximg2](https://user-images.githubusercontent.com/86812371/207794997-d22bd390-cb52-4e9d-9f2f-dcb38f7e7c93.png)

In line number 178 of the userchrome.css file change the value from 40px to 55px:
https://github.com/leadweedy/Firefox-Proton-Square/blob/main/userChrome.css#L178

Please comment if this fixed the problem.

**Comment by leadweedy** [comment]
it looks like FF108 had some changes that broke the custom tab height in CSS. ive temporarily disabled that option in the [v.1.6.9](https://github.com/leadweedy/Firefox-Proton-Square/releases/tag/v1.6.9) release until i can find a workaround.

the problematic lines are 107-118. before if you reduced the height of the tab, the contents would resize to fit. now, the contents just clip and cut off the top few pixels (hence the wierd looking tab line)

**Comment by leadweedy** [comment]
line 181 `transform: translateY(-20px) !important;` is no longer needed. looks to be more changes in FF108.
fixed in the re-release
