### ISSUE TITLE
Adding an option to hide the Unified Extensions Button

### ISSUE THREAD

**Issue by EktoHunter** [leadweedy/Firefox-Proton-Square#15]
Hey there, this isn't an issue but a feature request: Could you add an option to remove/hide the unified extensions button as mentioned [here (r/firefox/)](https://www.reddit.com/r/firefox/comments/11r85pf/comment/jc86z4w/?utm_source=share&utm_medium=web2x&context=3)?
In the previous version it was possible to do this over about:config but this is no longer possible. Maybe this could be added as an option in the userVariables.css

**Comment by leadweedy** [comment]
good suggestion, added in 01e7114c3e42586e687cb02d434360d72c4d003c.

**Comment by leadweedy** [comment]
it can be disabled with an about:config pref `browser.unifiedextensions.hide` = `true` in the latest release
