### ISSUE TITLE
Add option to change position of "Mute" button on the tab for Waterfox

### ISSUE THREAD

**Issue by EktoHunter** [leadweedy/Firefox-Proton-Square#17]
**Is your feature request related to a problem? Please describe.**
Yes, in Waterfox (a browser built on the Firefox source code) the "mute" button is misaligned as the Waterfox Theme Customizations change how the tabs are displayed:
![image](https://github.com/leadweedy/Firefox-Proton-Square/assets/23218251/d8e91680-29d1-4793-bfd0-dae565a530b2)
There customizations can be disabled, but then result in issues with the tab barriers and makes the X's to close the tabs look disproportionately small:
![image](https://github.com/leadweedy/Firefox-Proton-Square/assets/23218251/57e6c9f4-b02f-4862-ac42-98ddf248c42f)

**Describe the solution you'd like**
Maybe a user variable could be implemented that changes the position of the mute button somehow.

**Describe alternatives you've considered**
Alternatively the tab borders might be changed and the size of the X's if that's more convenient to implement.

**Additional context**
I completely understand if this won't be implemented, as Waterfox isn't the official Firefox and this will probably only affect like two people on the planet, I'm just kinda forced to use Waterfox on a special device that has issues with the Official Firefox. On my main device I still use the normal Firefox and am not encountering this issue.

There are some interesting features that Waterfox has in terms of customizability, with such things as a browser-wide script to try and make a lot of HTML elements that would be rounded squared, maybe @leadweedy could be interested in giving the browser a try to check if you like some of the customization options.

**Comment by leadweedy** [comment]
While I'm not looking to do a full Waterfox implementation, this is a good chance to make the divide line code a little more robust (i.e. dynamically calculated). My guess is that Waterfox is still using pre-FF108 source code, as some minor changes in that version required 00e26aaff40893365e599f8267d4746cee398990 to fix the tab line. 

Note that the X's in Waterfox are larger than normal. Here is stock Waterfox vs stock FF:
![Screenshot (3)](https://github.com/leadweedy/Firefox-Proton-Square/assets/72583854/26db1639-79b2-4844-ae4b-69effb135ed8)

The mute button can be moved, but there's a few additional animations in stock FF, like hiding the favicon. This is what it might look like without those additions:
![Screenshot (2)](https://github.com/leadweedy/Firefox-Proton-Square/assets/72583854/b524f07f-8336-4559-bc81-c332ca7a011c)

I'd prefer to fix just the tab borders, as moving the mute button and making it look right is more difficult. This is what it looks like with the new code (de99e7e3c5e847ae2c40441655995eb0db16de24) and customizations disabled:
![Screenshot (1)](https://github.com/leadweedy/Firefox-Proton-Square/assets/72583854/1e3f8bf5-89f7-41c3-b31c-5344bd1b8820)

If this is good enough for you, I'll go ahead and close the issue.

**Comment by EktoHunter** [comment]
Yeah that's fine

**Comment by leadweedy** [comment]
resolved with de99e7e3c5e847ae2c40441655995eb0db16de24
