### ISSUE TITLE
The way that preferences work has been changed

### ISSUE THREAD

**Issue by EktoHunter** [leadweedy/Firefox-Proton-Square#18]
**Describe the bug**
Currently, the option to hide the extensions button in the toolbar doesn't work (and presumably all other preferences set in about:config), since Mozilla apparently changed how `@supports` works, and it'll have to be changed to use `@media` instead.
[Reddit answer to my question regarding this not working](https://www.reddit.com/r/FirefoxCSS/comments/185iow0/comment/kb9d2zu/?utm_source=share&utm_medium=web2x&context=3)

**System Info (please complete the following information):**
- Windows 10
- Firefox 120.0

**Comment by leadweedy** [comment]
Thanks for bringing this up, I'll work on the fix.

**Comment by leadweedy** [comment]
fixed with https://github.com/leadweedy/Firefox-Proton-Square/commit/bc198c3f5f7d7da0108897fa5490cc97128b2398 and new release
