### ISSUE TITLE
Tab Dividers Hidden On Hover

### ISSUE THREAD

**Issue by Devo7v** [leadweedy/Firefox-Proton-Square#19]
**Is your feature request related to a problem? Please describe.**
When hovering over a non-active tab, the tab dividers (borders on the left and right of the tab) are hidden.

**Describe the solution you'd like**
Maintain the tab dividers in both light and dark mode.

**Describe alternatives you've considered**
None

**Additional context**
I'm not sure if this is a default Firefox thing since the tabs have been completely reconfigured, but this seems like an inconsistency.  I also read somewhere that visuallyselected is going to be deprecated at some point so you might want to check on that.

**Comment by leadweedy** [comment]
thanks for the report, i just confirmed in FF88 that having the tab dividers on hover was part of the original behavior, so this would be a bugfix. 
![image](https://github.com/leadweedy/Firefox-Proton-Square/assets/72583854/bf75c2b9-6ad6-47ea-86dd-006ba3cab032)

visuallyselected vs selected are functionally identical in the couple places theyre used, so ill go ahead and remove that

**Comment by leadweedy** [comment]
should be resolved with 05b241d5632cd98651cf787057803c14f03d9fb0 and 525ca219378a8f82c9fdf41e52f391fa496c8721, ill put out a release in a bit

**Comment by Devo7v** [comment]
I applied the changes and that solved everything.  Thanks so much for the quick turnaround, I really appreciate it.
