### ISSUE TITLE
Large tab sizes on Firefox 133

### ISSUE THREAD

**Issue by ThatRoboticFish** [leadweedy/Firefox-Proton-Square#24]
**Describe the bug**
After updating to Firefox 133, the tabs seem to be a little bit larger than before with this theme. However, if you start dragging or moving any tab, it returns to the original size but only while it's moving. 

**To Reproduce**
1. Install this CSS and update to Firefox 133

**Screenshots**
![imagen](https://github.com/user-attachments/assets/825af3de-0c7b-45d7-abc8-c2829fa6d9f5)
![imagen](https://github.com/user-attachments/assets/cce0dc49-27c8-40bc-8cdd-00404f3c6dd5)

**System Info (please complete the following information):**
 - OS: Windows 10
 - Firefox version: 133

**Comment by leadweedy** [comment]
thanks for the report, its now fixed in 04712c9960052178ada8c10f7ef3296853b2b974
