### ISSUE TITLE
Few questions!

### ISSUE THREAD

**Issue by Lakkkiy** [leadweedy/Firefox-Proton-Square#4]
Hello, really lie your styling of the tabs, thank you very much for the css. I don't really know much about it, so if you could help me figure some things, it would be awesome!
For some reason the accent coloring doesn't work, it still shows dark blue accents, even though I edited the color in the file.
And those tab separators are very weird for me, is there any way to remove them?

Thanks in advance, I really appreciate your work! 

![image](https://user-images.githubusercontent.com/74483879/149209888-63832e3d-0ba0-4b08-8305-0ffef80d9a7d.png)
![image](https://user-images.githubusercontent.com/74483879/149209743-543b9169-8c65-40fe-b1a1-5d49cc3ef11b.png)
![image](https://user-images.githubusercontent.com/74483879/149209767-18b203ae-910e-480c-a5ab-b4fa4b24374b.png)

Little update, figured out the color thing, I changed the color in the F12 style editor tab, and it seems to work!
![image](https://user-images.githubusercontent.com/74483879/149211652-1fac775a-df88-4e8d-9009-ece9a1cdb5d7.png)

**Comment by leadweedy** [comment]
Hm did you save the file and restart firefox to apply the changes when you edited the color? Since it works through the F12 editor, everything is imported correctly

**Comment by leadweedy** [comment]
The color of the tab separator is controlled by line 169 in userChrome.css: `background-color: #535354 !important;`. You can either change the hex color or remove the line entirely to disable it

**Comment by leadweedy** [comment]
Having a way to remove / or change the color of the tab separator is a good enhancement tho!

**Comment by Lakkkiy** [comment]
Thank you very much for the tips :) I looked through the code, but didn't assume tab separators were called like so, again thanks a lot, I really enjoy your UI changes!

**Comment by leadweedy** [comment]
color option added with eee88d11c5c4b82cd8812691a5901e9761b90a1b!
