### ISSUE TITLE
Button on Closing Multiple Tabs popup alert invisible.

### ISSUE THREAD

**Issue by Jgr9** [leadweedy/Firefox-Proton-Square#5]
**Describe the bug**
This makes the Close tabs button on the Closing Multiple Tabs warning popup invisible.

**To Reproduce**
1. Enable Confirm before closing multiple tabs
2. Close a window with multiple tabs

**Expected behavior**
The Close tabs button on the alert popup shouldn't be invisible.

**System Info (please complete the following information):**
 - OS: W10
 - Firefox version: 96

**Additional context**
I am using CustomCSSforFx by Aris as well, but I placed this stuff at the end.
Also Light themed, not dark.

I also only used userChrome.  I've now put together the squaring (userChrome) pieces I need and the issue isn't present now.  Something with the coloring section that I'm no longer using perhaps? idk

**Comment by leadweedy** [comment]
> I also only used userChrome

is the main cause of the issue. 

The userChrome imports the custom color it needs from `userVariables.css`, but since its not present, there color just becomes transparent. It would be a good idea to add a fallback color tho for cases like this.

**Comment by leadweedy** [comment]
It sounds like you aren't using the custom color section, which would avoid the issue. 

The entirety of the that section is based around the `--custom-accent-color` variable which gets imported from userVariables.css

**Comment by Jgr9** [comment]
Yeah leaving out the import at the top means no issue at all just using the userChrome (or just pieces of it).

**Comment by Jgr9** [comment]
Looks like you haven't done Settings?

**Comment by leadweedy** [comment]
leaving out the import would cause the issue I'd think, since the variable would be left empty. but using only pieces of the userChrome (i.e. leaving out the color section) works around it

**Comment by leadweedy** [comment]
the settings and other internal pages can't be controlled by userChrome, that's what the userContent does
