### ISSUE TITLE
Include this proper fix to rounded window corners in instructions

### ISSUE THREAD

**Issue by vipzerix** [leadweedy/Firefox-Proton-Square#7]
Credit: https://www.reddit.com/r/pop_os/comments/hnxgzv/i_have_been_trying_for_hours_to_get_rid_of_the/gbrmra7/

Affects all GTK applications including Firefox. Requires the user to add the following to `~/.config/gtk-3.0/gtk.css`:
```
decoration, window, window.background, window.titlebar, * {
border-radius: 0px;
}
```

While I'm here, I have a small question - I would like to make middle-click scroll actually not-square, but I can't find the line in your CSS that controls it. Thanks a lot for making this by the way, I'm new to Linux as well as Firefox.

**Comment by leadweedy** [comment]
Thanks for the suggestion! As it would happen, these two things are linked. The scroller was being inadvertently styled by the `slot` element for certain popups, but your GTK fix solves the issues with ALL popups (so it's not needed anymore). Props!

Scroller will no longer be square in the next release.

**Comment by leadweedy** [comment]
https://github.com/leadweedy/Firefox-Proton-Square/commit/0a1da702b2ba8e83f76eebe159091b69d2cf26d3
