### ISSUE TITLE
Add user variable to set padding between tabs

### ISSUE THREAD

**Issue by EktoHunter** [leadweedy/Firefox-Proton-Square#8]
On MacOS the Padding between the first tab and the window control is slightly too small, making the first tab look squished against the rest of the window controls.

Possible Solution: Include a User Variable to set the padding between tabs (/ tabs and window controls if that's possible.)
![Bildschirmfoto 2022-03-05 um 15 58 59](https://user-images.githubusercontent.com/23218251/156888971-f9330cfa-0b08-4e01-9d18-d5bedf7b6900.png)

**Comment by leadweedy** [comment]
fixed with https://github.com/leadweedy/Firefox-Proton-Square/commit/76109f0d3a137be04fe0ee28a1aadc6dcf18099a and https://github.com/leadweedy/Firefox-Proton-Square/commit/565e68cd6f7db212485542c2c0af0e4fbbf73816.

padding is re-enabled by default for macos
