### ISSUE TITLE
Rounded corners in List All Tabs menu

### ISSUE THREAD

**Issue by shizoid23** [leadweedy/Firefox-Proton-Square#9]
List All Tabs menu still has rounded corners on tab hover. Could you please fix this? Thanks!

**Comment by leadweedy** [comment]
Thanks for filing an issue. Can you include some more information:
- screenshot
- operating system
- Firefox version

**Comment by leadweedy** [comment]
scratch that, should be fixed by 134b8745e88de4261d11cb5ff00ef4641c9b56d4

![image](https://user-images.githubusercontent.com/72583854/165850577-0fc2d789-91ff-4eb8-8646-24ce72443241.png)
